version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - ./volumes/postgres/data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: m@m.com
#      PGADMIN_DEFAULT_PASSWORD: pgadmin
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - ./volumes/pgadmin/data:/var/lib/pgadmin
#
#    ports:
#      - "5050:80"
#    networks:
#      - postgres
#    restart: unless-stopped

networks:
  postgres:
    driver: bridge

#volumes:
#  postgres:
#  pgadmin: